server:
  port: 9191
spring:
  application:
    name: SERVICE-RECEIVERS

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${service_registry_url:http://localhost:8761/eureka/}
